import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const stepSource = await readFile('src/components/StepAiIntegration.tsx', 'utf8')
const appSource = await readFile('src/App.tsx', 'utf8')
const cssSource = await readFile('src/index.css', 'utf8')

assert.match(stepSource, /setReferenceDocs:\s*\(docs:\s*ReferenceDoc\[\]\)\s*=>\s*void/)
assert.match(stepSource, /referenceDocs=\{effectiveReferenceDocs\}/)
assert.match(stepSource, /setReferenceDocs=\{setReferenceDocs\}/)
assert.match(stepSource, /addButtonLabel="加入数据源"/)
assert.match(stepSource, /viewingReference/)
assert.match(stepSource, /title="查看全文"/)
assert.match(stepSource, /setViewingReference\(\{ doc, index: refIndex \}\)/)
assert.match(stepSource, /AI整合参考数据源/)
assert.match(stepSource, /viewingReference\.doc\.text\.trim\(\) \|\| '暂无可查看的解析文本'/)
assert.match(stepSource, /isClinicMasterReferenceDoc\(doc\)/)
assert.match(stepSource, /doc\.filename\.startsWith\('ClinMaster-'\)/)
assert.match(stepSource, /deleteReferenceDoc\(doc\.filename\)/)
assert.match(stepSource, /title="删除ClinMaster数据源"/)
assert.match(stepSource, /AI筛选切片/)
assert.match(stepSource, /确认切片/)
assert.match(stepSource, /reference_mode:\s*activeReferenceMode/)
assert.match(stepSource, /referenceMode:\s*activeReferenceMode/)
assert.match(stepSource, /setReferenceMode\('confirmed_chunks'\)/)
assert.match(stepSource, /setReferenceMode\('full'\)/)
assert.match(stepSource, /disabled=\{!canSearchReferenceChunks\}/)
assert.match(stepSource, /draftGuidelineReferenceChunks/)
assert.match(stepSource, /setDraftGuidelineReferenceChunks\(\[\]\)/)
assert.match(stepSource, /value=\{draftGuidelineReferenceChunks\}/)
assert.match(stepSource, /onChange=\{setDraftGuidelineReferenceChunks\}/)
assert.match(stepSource, /confirmAiChunkSearch/)
assert.match(stepSource, /discardAiChunkSearch/)
assert.match(stepSource, /setGuidelineReferenceChunks\(draftGuidelineReferenceChunks\)/)
assert.match(stepSource, /exitLabel="退出"/)
assert.match(stepSource, /onExit=\{discardAiChunkSearch\}/)
assert.match(stepSource, /当前已选择切片/)
assert.match(stepSource, /当前没选择切片/)
assert.match(stepSource, /选中的所有数据源/)
assert.match(stepSource, /不选择切片/)
assert.match(stepSource, /选择已确认切片/)
assert.match(stepSource, /disabled=\{!usingConfirmedReferenceChunks && guidelineReferenceChunks\.length === 0\}/)
assert.doesNotMatch(stepSource, /请先筛选并确认指南切片/)
const sendButtonIndex = stepSource.indexOf('发送')
const chunkSearchButtonIndex = stepSource.indexOf('AI筛选切片')
assert.ok(
  sendButtonIndex >= 0 && chunkSearchButtonIndex >= 0 && Math.abs(sendButtonIndex - chunkSearchButtonIndex) < 2500,
  'AI筛选切片按钮应放在发送按钮同一操作区附近',
)
const chunkSearchQueryBlock = stepSource.match(/const chunkSearchQuery[\s\S]*?\n  const setAllRefs/)?.[0] ?? ''
assert.match(chunkSearchQueryBlock, /disease/)
assert.match(chunkSearchQueryBlock, /userRequest/)
assert.doesNotMatch(chunkSearchQueryBlock, /originalContent/)
assert.doesNotMatch(chunkSearchQueryBlock, /selectedLinkedIssues/)
const generateRequestBlock = stepSource.match(/const generateRequestFromIssues[\s\S]*?\n  const deleteRecord/)?.[0] ?? ''
assert.match(generateRequestBlock, /setUserRequest/)
assert.match(generateRequestBlock, /setGuidelineReferenceChunks\(\[\]\)/)
assert.match(generateRequestBlock, /setDraftGuidelineReferenceChunks\(\[\]\)/)
assert.match(generateRequestBlock, /setReferenceMode\('full'\)/)
assert.match(generateRequestBlock, /setChunkPanelOpen\(false\)/)
assert.doesNotMatch(stepSource, /clinicMasterReferenceChunks/)
assert.doesNotMatch(stepSource, /onConfirmReferenceChunks=\{setClinicMasterReferenceChunks\}/)
assert.match(appSource, /setReferenceDocs=\{handleSetReferenceDocs\}/)
assert.match(cssSource, /\.btn-m3-outline:disabled/)
assert.match(cssSource, /\.btn-m3-outline:hover:not\(:disabled\)/)

console.log('StepAiIntegration ClinicMaster tests passed')
